typography_spectrum: 0.944596050074324
color:
  brandStrength: 0.12297182762995362
  lightness: 0.4194523529149592
  saturation: 0.6966515830717981
  rhythmicContrast: 0.5348527519963682
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
layout_spectrum: 0.2510287424083799
author:
  name: Vyacheslav Kuleshov
  email: k.v@mac.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/38768a01-0c0b-4a31-9c58-70da215f13d7.png
name: Gauf & Partners
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/24bdc306-b80a-4756-923e-ad9f116ceca3.ico
title: адвокатские услуги
description: адвокатские услуги
